### ISSUE TITLE
build.fsx Not working on Mac

### ISSUE THREAD

**Issue by alfonsogarciacaro** [tpetricek/Pollz#1]
I get the following error:

```
System.NotImplementedException: The method or operation is not implemented.
  at System.Net.NetworkInformation.UnixIPGlobalProperties.GetActiveTcpListeners () <0xb3ca518 + 0x0001f> in <filename unknown>:0 
```

This indicates `GetActiveTcpListeners ()` it's not implemented in Mono. A solution to fix is to remove the call to `findPort` in line 80 and just set the port directly

**Comment by tpetricek** [comment]
I removed the port scanning from `build.fsx` so this is now fixed.
